# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Run a single replicate individual-based simulation
#' @param ngenerations Number of generations (integer)
#' @export
#' @rawNamespace importFrom(Rcpp,sourceCpp);useDynLib(mutualismLH);
ibm <- function(ngenerations) {
    .Call('_mutualismLH_ibm', PACKAGE = 'mutualismLH', ngenerations)
}

